name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./LampColorControler

    steps:
    - uses: actions/checkout@v4
      with:
        path: LampColorControler
        submodules: 'true'
    - name: setup
      run : make mr_proper arduino-cli-download safe-install
    - name: verify format
      run : make format-verify
    # MISSING build for simu:  no X11 on headless github serves
    - name: Documentation
      run : make doc
    - name: simple led strip build
      run : make simple
    - name: cct led strip build
      run : make cct
    - name: indexable led strip build
      run : make indexable
